import CCOIcons from "src/typedefs";

const boxSchema = {
    "series1": {
        "name": "Cube Series #1",
        "type": "cube",
        "contents": [
            "bluecamo",
            "redcamo",
            "pinkcamo",
            "bluemushroom",
            "redmushroom",
            "yellowmushroom",
            "autumnleaves",
            "pinktarget",
            "iron",
            "hologram",
            "greengrass",
            "holey",
            "boom",
            "mosaica",
            "invisible",
            "gold",
            "emerald",
            "copper",
            "sushi",
            "chicken",
            "dice",
            "tv",
            "neon",
            "therelic",
            "crust",
            "aspects",
            "kyanite",
            "crtmonitor",
            "weirdearth",
            "unrealgreen",
            "plaguecapsule",
            "sublime",
            "glacial",
            "oddmush"
        ]
    },
    "series2": {
        "name": "Cube Series #2",
        "type": "cube",
        "contents": [
            "redbuildingblock",
            "bluebuildingblock",
            "greencamo",
            "greentarget",
            "greenmushroom",
            "bluetarget",
            "burrito",
            "yelloweye",
            "redtarget",
            "purpletarget",
            "aries",
            "aquarius",
            "redeye",
            "pillar",
            "redgalaxy",
            "pinkgalaxy",
            "purplegalaxy",
            "minty",
            "gluttony",
            "bluenebula",
            "rednebula",
            "purplenebula",
            "earth",
            "planarsilk",
            "plastique",
            "mutes",
            "binary",
            "peppermint",
            "truerelic",
            "unrealgreen",
            "plaguecapsule",
            "sublime",
            "glacial",
            "oddmush"
        ]
    },
    "series3": {
        "name": "Cube Series #3",
        "type": "cube",
        "contents": [
            "yellow",
            "pinkbuildingblock",
            "greenbuildingblock",
            "bean",
            "redgrass",
            "pinkcheckered",
            "maze",
            "barrel",
            "pancake",
            "steel",
            "gemini",
            "capricorn",
            "cancer",
            "aries",
            "bluegalaxy",
            "flamesteel",
            "yellowgalaxycube",
            "bakedpotato",
            "redbutton",
            "bluebutton",
            "configurum",
            "blooming",
            "cat",
            "orichalcum",
            "cake",
            "cubeonastick",
            "buddy",
            "bismuth",
            "brimstone",
            "unrealgreen",
            "plaguecapsule",
            "sublime",
            "glacial",
            "oddmush"
        ]
    },
    "series4": {
        "name": "Cube Series #4",
        "type": "cube",
        "contents": [
            "blackcheckered",
            "red",
            "black",
            "white",
            "pinkgoo",
            "bluegoo",
            "greengoo",
            "pinkcrystal",
            "bluecrystal",
            "greencrystal",
            "glass",
            "scorpio",
            "sagittarius",
            "pisces",
            "obsidian",
            "sapphire",
            "rustedcube",
            "mossymetal",
            "distorted",
            "gilded",
            "hay",
            "ultrahd",
            "meaty",
            "greenbutton",
            "durasteel",
            "delusional",
            "adamantium",
            "sheenobsidian",
            "ruby",
            "unrealgreen",
            "plaguecapsule",
            "sublime",
            "glacial",
            "oddmush"
        ]
    },
    "series5": {
        "name": "Cube Series #5",
        "type": "cube",
        "contents": [
            "purple",
            "green",
            "blue",
            "pinkmushroom",
            "pinkeye",
            "redgoo",
            "aquarium",
            "ghostly",
            "rock",
            "redcrystal",
            "virgo",
            "taurus",
            "valentines",
            "olive",
            "corn",
            "arcade",
            "supreme",
            "melting",
            "tabby",
            "upsidedown",
            "broken",
            "foursided",
            "cowardly",
            "terrarium",
            "deathly",
            "psychedelic",
            "neonoir",
            "neonoirmk2",
            "illuminati",
            "unrealgreen",
            "plaguecapsule",
            "sublime",
            "glacial",
            "oddmush"
        ]
    },
    "series6": {
        "name": "Cube Series #6",
        "type": "cube",
        "contents": [
            "greenstriped",
            "bluestriped",
            "saltine",
            "redwireframe",
            "greenwireframe",
            "purplemushroom",
            "reallybig",
            "redblock",
            "blueblock",
            "pinkblock",
            "brick",
            "aliengrass",
            "demonsteel",
            "watching",
            "forwardfacing",
            "battery",
            "dragonglass",
            "feathered2",
            "feathered",
            "creepy",
            "popcorn",
            "deductory",
            "missing",
            "synthesizing",
            "fade",
            "cardboardbox",
            "rebar",
            "eventhorizon",
            "unrealgreen",
            "plaguecapsule",
            "sublime",
            "glacial",
            "oddmush"
        ]
    },
    "series7": {
        "name": "Cube Series #7",
        "type": "cube",
        "contents": [
            "purplestriped",
            "pinkstriped",
            "pink",
            "orangewireframe",
            "purplewireframe",
            "pinkwireframe",
            "greenfabric",
            "bluefabric",
            "mountainous",
            "sunny",
            "pinkice",
            "ice",
            "cinderblock",
            "bluebook",
            "brownbook",
            "leadbasedpaint",
            "refracting",
            "shoji3",
            "shoji2",
            "shoji1",
            "opal2",
            "opal1",
            "feathered3",
            "polyphemus",
            "working",
            "shimmering",
            "hilbert",
            "unpossible",
            "impossible",
            "unrealgreen",
            "plaguecapsule",
            "sublime",
            "glacial",
            "oddmush"
        ]
    },
    "series8": {
        "name": "Cube Series #8",
        "type": "cube",
        "contents": [
            "yellowstriped",
            "whitegoo",
            "redstriped",
            "bluejumble",
            "childsafe",
            "bluewireframe",
            "petrified2",
            "petrified1",
            "redfabric",
            "pinkfabric",
            "ducky",
            "greenice",
            "redice",
            "pandoras",
            "crimson",
            "velvet",
            "greenbook",
            "dog",
            "oldfashionedtv",
            "autumn",
            "clover",
            "terminal",
            "shoji4",
            "teensy",
            "cubeswarm",
            "cautionary",
            "chivalrous",
            "rgb",
            "unrealgreen",
            "plaguecapsule",
            "sublime",
            "glacial",
            "oddmush"
        ]
    },
    "series9": {
        "name": "Cube Series #9",
        "type": "cube",
        "contents": [
            "bluepill",
            "redpill",
            "greenpill",
            "pinkjumble",
            "greenjumble",
            "redjumble",
            "greentiles",
            "bluetiles",
            "petrified4",
            "petrified3",
            "bluemarble",
            "greenmarble",
            "redmarble",
            "gasoline",
            "splatter1",
            "horus2",
            "horus1",
            "meteorite",
            "pond",
            "ballin",
            "bear",
            "apple",
            "tp",
            "dog2",
            "bluecore",
            "older",
            "banded",
            "blackmarble",
            "octacube",
            "unrealgreen",
            "plaguecapsule",
            "sublime",
            "glacial",
            "oddmush"
        ]
    },
    "series10": {
        "name": "Cube Series #10",
        "type": "cube",
        "contents": [
            "bluebubble",
            "yellowpill",
            "purplepill",
            "greencrumbling",
            "bluecrumbling",
            "landmass",
            "collegeruled",
            "plum",
            "orange",
            "pinktiles",
            "firegem",
            "vaporwave",
            "yellowmarble",
            "bluemarble",
            "dusk",
            "arizona",
            "splatter3",
            "splatter2",
            "clock",
            "tornpolaroid",
            "watamelon",
            "raccoon",
            "bunny",
            "calico",
            "frog",
            "meltinggreen",
            "redcore",
            "altar",
            "idol",
            "unrealgreen",
            "plaguecapsule",
            "sublime",
            "glacial",
            "oddmush"
        ]
    },
    "series11": {
        "name": "Cube Series #11",
        "type": "cube",
        "contents": [
            "lame",
            "pinkbubble",
            "greenbubble",
            "pinkflower",
            "blueflower",
            "yellowcrumbling",
            "fries",
            "burger",
            "pomegranate",
            "orangebox",
            "aerogel",
            "garter",
            "oceano",
            "firegem",
            "shunned",
            "worshipped",
            "neglected",
            "retro",
            "redslime",
            "pinkslime",
            "greenslime",
            "blueslime",
            "barn",
            "mango",
            "looking",
            "turtle",
            "beach",
            "pretzelburger",
            "diamond",
            "unrealgreen",
            "plaguecapsule",
            "sublime",
            "glacial",
            "oddmush"
        ]
    },
    "misfit": {
        "name": "Misfit Cube Series",
        "type": "cube",
        "contents": [
            "Greenfoliage",
            "redfoliage",
            "bluefoliage",
            "ultralame",
            "pinkpastel",
            "bluepastel",
            "purpleflower",
            "orangeflower",
            "greencup",
            "bluecup",
            "softdrink",
            "hotdog",
            "angry",
            "honey",
            "magatsu",
            "stone1",
            "monkey",
            "paranoid",
            "log",
            "interrobang",
            "dregs",
            "soup",
            "yellowslime",
            "bomb",
            "lunchbox",
            "cherry",
            "coobcyoob",
            "constellation",
            "sun",
            "unrealgreen",
            "plaguecapsule",
            "sublime",
            "glacial",
            "oddmush"
        ]
    },
    "cool": {
        "name": "Cool Cube Series",
        "type": "cube",
        "contents": [
            "greenglowstick",
            "redglowstick",
            "yellowglowstick",
            "blueglowstick",
            "redpokerchip",
            "bluepokerchip",
            "redpastel",
            "greenpastel",
            "chocolate",
            "redcup",
            "yellowcup",
            "beefcube",
            "worried",
            "derpycubeorsumidk",
            "calm",
            "bellpepper",
            "stone4",
            "stone3",
            "stone2",
            "loading",
            "orangefruit",
            "turf",
            "pathing",
            "miniminotaur",
            "cubitos",
            "cleaners",
            "tree",
            "ultrawide",
            "gamingpc",
            "unrealgreen",
            "plaguecapsule",
            "sublime",
            "glacial",
            "oddmush"
        ]
    },
    "supporter": {
        "name": "Supporter Cube Series",
        "type": "cube",
        "contents": [
            "orangedonut",
            "greendonut",
            "bluedonut",
            "browntable",
            "bluetable",
            "purplepokerchip",
            "pinkpokerchip",
            "tombstone",
            "beehive",
            "basket",
            "butter",
            "sobbing",
            "linoleum",
            "yinyang",
            "cinnamonroll",
            "cobbled",
            "stove",
            "bee",
            "zsaga",
            "saturn",
            "marble",
            "treasuremap",
            "tiger",
            "moon",
            "waterfall",
            "scrambling",
            "henry",
            "unrealgreen",
            "plaguecapsule",
            "sublime",
            "glacial",
            "oddmush"
        ]
    },
    "nitro": {
        "name": "Nitro Cube Series",
        "type": "cube",
        "contents": [
            "purpledonut",
            "pinkdonut",
            "redtable",
            "greentable",
            "diamondsuit",
            "heartsuit",
            "spadesuit",
            "clubsuit",
            "bread",
            "baseball",
            "luckysevens",
            "strawberryroll",
            "lake",
            "infinity",
            "meatball",
            "undead",
            "stitched",
            "coolcat",
            "cubeonanotherstick",
            "unrealgreen",
            "plaguecapsule",
            "sublime",
            "glacial",
            "oddmush"
        ]
    },
    "weirdo": {
        "name": "Weirdo Cube Series",
        "type": "specialcube",
        "contents": [
            "bash",
            "pensive",
            "greenradar",
            "sunset",
            "ghost",
            "pig",
            "melon",
            "lenny",
            "desertcamo",
            "cow",
            "superheated",
            "spartan",
            "deepsea",
            "speaker",
            "axolotl",
            "cubeofccc",
            "coral",
            "cub",
            "venus",
            "koala",
            "fox",
            "floppa",
            "flushed",
            "supercooled",
            "unrealgreen",
            "plaguecapsule",
            "sublime",
            "glacial",
            "oddmush"
        ]
    },
    "spring1": {
        "name": "Spring Cube Series",
        "type": "cube",
        "contents": [
            "ooshersmime",
            "ooshersmagma",
            "ooshersrainbow",
            "linksmud",
            "linksbongo",
            "linksboil",
            "ooshersfountain",
            "oosherscloud",
            "oosherstree",
            "linksriver",
            "linkssprout",
            "linksflowers",
            "linksbutterfly",
            "ooshersfossil",
            "ooshers3dprinter",
            "linkslobster",
            "linkslightning",
            "ooshersglitched",
            "linkskimono",
            "linksskeleton",
            "unrealgreen",
            "plaguecapsule",
            "sublime",
            "glacial",
            "oddmush"
        ]
    },
    "summer1": {
        "name": "Summer Cube Series",
        "type": "cube",
        "contents": [
            "purplepopsi",
            "redpopsi",
            "greenpopsi",
            "bluepopsi",
            "greenshell",
            "yellowshell",
            "purpleshell",
            "pinkshell",
            "umb3",
            "umb2",
            "umb1",
            "sandcastle",
            "beachball",
            "fireworks",
            "clownfish",
            "salamander",
            "shore",
            "bubbly",
            "waves",
            "shark",
            "whale",
            "pier",
            "lifepreserver",
            "unrealgreen",
            "plaguecapsule",
            "sublime",
            "glacial",
            "oddmush"
        ]
    },
    "fools": {
        "name": "Fool's Series",
        "type": "cube",
        "contents": [
            "bozogreen",
            "bozopink",
            "bozored",
            "bozoblue",
            "milkbrown",
            "milk",
            "milkpink",
            "unicycle",
            "smug",
            "mischievous",
            "joker",
            "aspectsgaze",
            "troll",
            "unrealgreen",
            "plaguecapsule",
            "sublime",
            "glacial",
            "oddmush"
        ]
    },
    "aspects": {
        "name": "Aspect's Arsenal",
        "type": "cube",
        "contents": [
            "redsplatcyub",
            "greensplatcyub",
            "bluesplatcyub",
            "pinksplatcyub",
            "greentubchair",
            "bluetubchair",
            "purpletubchair",
            "redtubchair",
            "fist",
            "coders",
            "aspectcircuit",
            "aspectcircuittwo",
            "yellowspray",
            "redspray",
            "pinkspray",
            "greenspray",
            "cyanspray",
            "bluespray",
            "cutesy",
            "propaganda",
            "happe",
            "snail",
            "stock",
            "nostalgic2",
            "nostalgic",
            "coffeemug",
            "badass",
            "iris",
            "unrealgreen",
            "plaguecapsule",
            "sublime",
            "glacial",
            "oddmush"
        ]
    },
    "spooky": {
        "name": "Spooky Cube Series",
        "type": "cube",
        "contents": [
            "pumpkin",
            "freaky",
            "jackolantern3",
            "jackolantern2",
            "jackolantern1",
            "hunkofmeat",
            "rotten",
            "poltergeist",
            "cubeofmanyfaces",
            "candle",
            "speakno",
            "hearno",
            "seeno",
            "lurking",
            "desolate",
            "monolithic",
            "mourning",
            "minoscube",
            "blackcat",
            "4dpumpkin",
            "unrealgreen",
            "plaguecapsule",
            "sublime",
            "glacial",
            "oddmush"
        ]
    },
    "emote": {
        "name": "Emote Cube Series",
        "type": "cube",
        "contents": [
            "ayaya",
            "kekw",
            "pogemote",
            "5head",
            "yepemote",
            "monkaw",
            "pepel",
            "pepehmm",
            "wickedemote",
            "popcat",
            "sadgecube",
            "pepega",
            "ezemote",
            "pepelaugh",
            "peperee",
            "pepecringe",
            "pepeclown",
            "pepepoggers",
            "unrealgreen",
            "plaguecapsule",
            "sublime",
            "glacial",
            "oddmush"
        ]
    },
    "community1": {
        "name": "Community Cube Collection 1",
        "type": "cube",
        "contents": [
            "strawberry",
            "pineapple",
            "gradient2",
            "gradient1",
            "whitehole",
            "uranus",
            "airconditioner",
            "highasfuck",
            "holywarrior",
            "unholywarrior",
            "penguin",
            "ladybug",
            "hoverboard",
            "satellite",
            "you",
            "fourdee",
            "unrealgreen",
            "plaguecapsule",
            "sublime",
            "glacial",
            "oddmush"
        ]
    },
    "community2": {
        "name": "Community Cube Collection 2",
        "type": "cube",
        "contents": [
            "abstractone",
            "abstracttwo",
            "abstractthree",
            "xviremix",
            "peekacube",
            "twirling",
            "celebratory",
            "mouth",
            "lunarflare",
            "weirdbox",
            "pulsar",
            "lasertag",
            "rottinglog",
            "raccoontwo",
            "ofthewatchers",
            "vantablackfourdee",
            "virginslayer",
            "unrealgreen",
            "plaguecapsule",
            "sublime",
            "glacial",
            "oddmush"
        ]
    },
    "sdoma": {
        "name": "Sdoma Series",
        "type": "specialcube",
        "contents": [
            "signaturecircuit",
            "orbitingcircuit",
            "etchedcircuit",
            "blackcircuit",
            "circuit",
            "shortcircuit",
            "expandingcircuit",
            "breathingcircuit",
            "rainbowcircuit",
            "unrealgreen",
            "plaguecapsule",
            "sublime",
            "glacial",
            "oddmush"
        ]
    },
    "autumnal": {
        "name": "Autumnal Series",
        "type": "cube",
        "contents": [
            "autumnleaf4",
            "autumnleaf3",
            "autumnleaf2",
            "autumnleaf1",
            "firehydrant2",
            "firehydrant1",
            "coolmush2",
            "coolmush1",
            "nest",
            "tumbleweed",
            "compactedspice",
            "brownpaperbag",
            "jamdanish",
            "pipebomb",
            "tomatosoup",
            "splitrail",
            "acorn",
            "dogg",
            "pumpkinspicelatte",
            "unrealgreen",
            "plaguecapsule",
            "sublime",
            "glacial",
            "oddmush"
        ]
    },
    "christmas1": {
        "name": "Naughty and Nice Series",
        "type": "cube",
        "contents": [
            "redcandycane",
            "greencandycane",
            "bluecandycane",
            "pinkcandycane",
            "redgift",
            "bluegift",
            "joshpresent",
            "festivegreen",
            "cookie",
            "reindeer",
            "elf",
            "santa",
            "chimney",
            "rudolph",
            "snowman",
            "festiveocta",
            "festiveimpossible",
            "unrealgreen",
            "plaguecapsule",
            "sublime",
            "glacial",
            "oddmush"
        ]
    },
    "valentines1": {
        "name": "Romantical Series",
        "type": "cube",
        "contents": [
            "pinkvillabrick",
            "greenvillabrick",
            "bluevillabrick",
            "redvillabrick",
            "redchocobox",
            "pinkchocobox",
            "greenchocobox",
            "bluechocobox",
            "vf3",
            "vf2",
            "vf1",
            "unsignedletter",
            "loveletter",
            "hateletter",
            "rabbitplush",
            "beary",
            "cupidsarrow",
            "heartonastick",
            "spacedust",
            "kissing",
            "hateful",
            "aphrodite",
            "unrealgreen",
            "plaguecapsule",
            "sublime",
            "glacial",
            "oddmush"
        ]
    },
    "discontinued": {
        "name": "Discontinued Series",
        "type": "cube",
        "contents": [
            "fire",
            "basketball",
            "goodbye",
            "welcome",
            "giraffe",
            "suit",
            "anime",
            "woqas",
            "sloth",
            "dreamy",
            "parallaxxs",
            "sdomas",
            "orthographic",
            "duck",
            "opulent",
            "lamentable",
            "manncube",
            "omnis",
            "hollow",
            "erupting",
            "infernos",
            "servercustomcube",
            "meru",
            "cubekabob",
            "unrealgreen",
            "plaguecapsule",
            "sublime",
            "glacial",
            "oddmush"
        ]
    },
    "cataclysmic": {
        "name": "Cataclysmic Collection",
        "type": "cube",
        "contents": [
            "wormhole",
            "blackhole",
            "climatechanged",
            "earthquake",
            "hurricane",
            "cyclone",
            "famine",
            "ufolaser",
            "locust",
            "meteor",
            "nuked",
            "volcano",
            "forestfire",
            "tornado",
            "tsunami",
            "storm",
            "unrealgreen",
            "plaguecapsule",
            "sublime",
            "glacial",
            "oddmush"
        ]
    },
    "tarot": {
        "name": "Tarot Collection",
        "type": "cube",
        "contents": [
            "tarot3",
            "tarot2",
            "tarot1",
            "tarot6",
            "tarot5",
            "tarot4",
            "tarot9",
            "tarot8",
            "tarot7",
            "tarot12",
            "tarot11",
            "tarot10",
            "tarot15",
            "tarot14",
            "tarot13",
            "tarot18",
            "tarot17",
            "tarot16",
            "tarot20",
            "tarot19",
            "tarot22",
            "tarot21",
            "unrealgreen",
            "plaguecapsule",
            "sublime",
            "glacial",
            "oddmush"
        ]
    },
    "character": {
        "name": "Character Collection",
        "type": "specialcube",
        "contents": [
            "key0",
            "key9",
            "key8",
            "key7",
            "key6",
            "key5",
            "key4",
            "key3",
            "key2",
            "key1",
            "keyz",
            "keyy",
            "keyx",
            "keyw",
            "keyv",
            "keyu",
            "keyt",
            "keys",
            "keyr",
            "keyq",
            "keyp",
            "keyo",
            "keyn",
            "keym",
            "keyl",
            "keyk",
            "keyj",
            "keyi",
            "keyh",
            "keyg",
            "keyf",
            "keye",
            "keyd",
            "keyc",
            "keyb",
            "keya",
            "unrealgreen",
            "plaguecapsule",
            "sublime",
            "glacial",
            "oddmush"
        ]
    },
    "super": {
        "name": "Super Cube Series",
        "type": "cube",
        "contents": [
            "bluealien",
            "yellowdonut",
            "reddonut",
            "puzzle",
            "pencil",
            "waffle",
            "forestfloor",
            "whitetable",
            "soda3",
            "soda2",
            "soda1",
            "lemon",
            "cloudy",
            "tofu",
            "pillbottle",
            "peanutbutter",
            "jam",
            "nuclear",
            "uriel",
            "gabriel",
            "cubehub",
            "drug",
            "cuteshark",
            "rose",
            "object",
            "polarbear",
            "snowfox",
            "panda",
            "sponge",
            "butt",
            "monocuba",
            "unsettling",
            "realco0b",
            "unrealgreen",
            "plaguecapsule",
            "sublime",
            "glacial",
            "oddmush"
        ]
    },
    "duper": {
        "name": "Duper Cube Series",
        "type": "cube",
        "contents": [
            "redalien",
            "purplealien",
            "greenalien",
            "yellowbulb",
            "redbulb",
            "bluebulb",
            "qubit",
            "quark",
            "wrestling",
            "marshmallow",
            "basesixtyfour",
            "basetencube",
            "no",
            "deepspace",
            "strawhat",
            "cigarette",
            "grease",
            "mirror",
            "kiwi",
            "skin",
            "island",
            "mercury",
            "mars",
            "bottomless",
            "copycat",
            "toad",
            "bunnycosmo",
            "skull",
            "unrealgreen",
            "plaguecapsule",
            "sublime",
            "glacial",
            "oddmush"
        ]
    },
    "nolife": {
        "name": "No Life Series",
        "type": "cube",
        "contents": [
            "redgrinning",
            "greengrinning",
            "bluegrinning",
            "pufferfish",
            "duckling",
            "pear",
            "goldenapple",
            "roundearth",
            "flatearth",
            "dancefloor",
            "groovin",
            "bulletproofglass",
            "chemicalhazard",
            "staring",
            "sandstorm",
            "jail",
            "franklin",
            "redmonolithic",
            "purplemonolithic",
            "goldmonolithic",
            "cyanmonolithic",
            "brownmonolithic",
            "bluemonolithic",
            "desk",
            "creambear",
            "unrealgreen",
            "plaguecapsule",
            "sublime",
            "glacial",
            "oddmush"
        ]
    },
    "hazardous": {
        "name": "Hazardous Materials Box",
        "type": "cube",
        "contents": [
            "yellowhazmat",
            "redhazmat",
            "greenhazmat",
            "ucore",
            "tcore",
            "ionizing2",
            "ionizing1",
            "radonore",
            "iridiumore",
            "kunziteore",
            "quantum",
            "darkmatter",
            "hazneustar",
            "pulsingalien",
            "hazbarrel",
            "radium",
            "aldrins",
            "hanz",
            "unrealgreen",
            "plaguecapsule",
            "sublime",
            "glacial",
            "oddmush"
        ]
    },
    "mundane": {
        "name": "Mundane Series",
        "type": "cube",
        "contents": [
            "pinkcoffeetable",
            "greencoffeetable",
            "bluecoffeetable",
            "coffeetable",
            "greentoaster",
            "bluetoaster",
            "pinktoaster",
            "redtoaster",
            "toaster",
            "reddrawers",
            "greendrawers",
            "bluedrawers",
            "yellowdrawers",
            "whitedrawers",
            "blueottoman",
            "greenottoman",
            "ottoman",
            "rugtwo",
            "rugone",
            "cubybara",
            "fridgec",
            "winebottle",
            "tablet",
            "grill",
            "bed",
            "unrealgreen",
            "plaguecapsule",
            "sublime",
            "glacial",
            "oddmush"
        ]
    },
    "trash": {
        "name": "Trash Collection",
        "type": "cube",
        "contents": [
            "redjar",
            "purplejar",
            "bluejar",
            "greenjar",
            "greenbrokenbottle",
            "redbrokenbottle",
            "bluebrokenbottle",
            "pinkplasticbottle",
            "orangeplasticbottle",
            "blueplasticbottle",
            "compacteddust",
            "smashedtablet",
            "twistedmetal",
            "plasticrings",
            "tire",
            "sewage",
            "rottenpepper",
            "rotted",
            "unrealgreen",
            "plaguecapsule",
            "sublime",
            "glacial",
            "oddmush"
        ]
    },
    "nightmarish": {
        "name": "Nightmarish Series",
        "type": "cube",
        "contents": [
            "demon",
            "redseaserpent",
            "greenseaserpent",
            "blueseaserpent",
            "mythhelmetthree",
            "mythhelmettwo",
            "mythhelmetone",
            "paradragon",
            "australian",
            "medusa",
            "cthulu",
            "dragon",
            "unrealgreen",
            "plaguecapsule",
            "sublime",
            "glacial",
            "oddmush"
        ]
    },
    "collectors": {
        "name": "Collector's Collection",
        "type": "cube",
        "contents": [
            "blueterra",
            "purpleterra",
            "redterra",
            "orangeterra",
            "greenuhdtargetcube",
            "reduhdtargetcube",
            "blueuhdtargetcube",
            "purpleuhdtargetcube",
            "sed",
            "whitebaked",
            "moony",
            "realisticbee",
            "margarine",
            "mellting",
            "unsoundbrickcube",
            "completelynormal",
            "piano",
            "rooster",
            "hen",
            "ham",
            "amber",
            "redsafebutton",
            "greensafebutton",
            "picklejar",
            "cvsreceipt",
            "mongey",
            "rustedadamantite",
            "fakecoobcyoob",
            "grandpiano",
            "reworkedstormcube",
            "unrealgreen",
            "plaguecapsule",
            "sublime",
            "glacial",
            "oddmush"
        ]
    },
    "community3": {
        "name": "Community Cube Collection 3",
        "type": "cube",
        "contents": [
            "paranagiri",
            "mangocone",
            "paracone",
            "linkboredguy",
            "linkballotbox",
            "linksneapolitan",
            "linkshoneycomb",
            "linkfawkes",
            "linksgem",
            "linksfreoncube",
            "linksvines",
            "mangoindustrial",
            "linksmilkshake",
            "mangospolluted",
            "linksradish",
            "linksninja",
            "linkswolf",
            "sneejmime",
            "sneejcd",
            "unrealgreen",
            "plaguecapsule",
            "sublime",
            "glacial",
            "oddmush"
        ]
    },
    "entropy": {
        "name": "Entropy Series",
        "type": "cube",
        "contents": [
            "barcode",
            "striped",
            "static",
            "houndstooth",
            "topographical",
            "infested",
            "heartratemonitor",
            "sweeper",
            "polkacapsule",
            "chalkboard",
            "elixir",
            "perceiving",
            "confetti",
            "racerhelmet",
            "eclipse",
            "general",
            "emo",
            "twilight",
            "unrealgreen",
            "plaguecapsule",
            "sublime",
            "glacial",
            "oddmush"
        ]
    },
    "fractal": {
        "name": "Fractal Series",
        "type": "cube",
        "contents": [
            "transitional",
            "translational",
            "circumscribed",
            "tilated",
            "hemholtz",
            "negativespace",
            "spearmint",
            "imperialpattern",
            "menger",
            "sierpinski",
            "complexion",
            "mandelbrot",
            "dragoncurve",
            "hilbertcurve"
        ]
    }
} as const satisfies {[key: string]: {name: string, type: "cube" | "specialcube", contents: CCOIcons.cubeID[]}}

type boxID = keyof typeof boxSchema;

export {
    boxID,
    boxSchema
}
